SELECT
  (SELECT COUNT(*) FROM categories) categories,
  (SELECT COUNT(*) FROM collections) collections,
  (SELECT COUNT(*) FROM products) products,
  (SELECT COUNT(*) FROM discount_codes) discount_codes,
  (SELECT COUNT(*) FROM store_settings) store_settings,
  (SELECT COUNT(*) FROM shipping_methods) shipping_methods,
  (SELECT COUNT(*) FROM users) users,
  (SELECT COUNT(DISTINCT slug) FROM products) distinct_product_slugs,
  (SELECT COUNT(DISTINCT code) FROM discount_codes) distinct_discount_codes,
  (SELECT COUNT(*) FROM products p WHERE NOT EXISTS (SELECT 1 FROM categories c WHERE c.id = p.category_id)) orphan_product_category,
  (SELECT COUNT(*) FROM product_collections pc WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = pc.product_id) OR NOT EXISTS (SELECT 1 FROM collections c WHERE c.id = pc.collection_id)) orphan_product_collections,
  (SELECT COUNT(*) FROM product_images pi WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = pi.product_id)) orphan_images,
  (SELECT COUNT(*) FROM product_materials pm WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = pm.product_id)) orphan_materials,
  (SELECT COUNT(*) FROM product_options po WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = po.product_id)) orphan_options,
  (SELECT COUNT(*) FROM product_option_values pov WHERE NOT EXISTS (SELECT 1 FROM product_options po WHERE po.id = pov.option_id)) orphan_option_values,
  (SELECT COUNT(*) FROM product_customizations pc2 WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = pc2.product_id)) orphan_customizations,
  (SELECT COUNT(*) FROM product_special_request sr WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = sr.product_id)) orphan_special_request,
  (SELECT COUNT(*) FROM product_deposit d WHERE NOT EXISTS (SELECT 1 FROM products p WHERE p.id = d.product_id)) orphan_deposit;
